//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApplications.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public Answer()
        {
            this.Qualifications = new HashSet<Qualification>();
        }
    
        public int ID { get; set; }
        public int QuestionID { get; set; }
        public string Text { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsAcceptable { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual ICollection<Qualification> Qualifications { get; set; }
    }
}
