//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApplications.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualification
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public int QuestionID { get; set; }
        public int AnswerID { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Application Application { get; set; }
        public virtual Question Question { get; set; }
    }
}
